apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dnb-automation
  namespace: openshift-gitops
spec:
  destination:
    namespace: openshift-operators
    server: https://kubernetes.default.svc
  project: default
  source:
    directory:
      recurse: true
    path: create
    repoURL: https://github.com/pdragset/Automation_GitOps
    targetRevision: HEAD