apiVersion: argoproj.io/v1alpha1
kind: Subscription
metadata:
  name: ibm-mq
  namespace: openshift-operators 
  annotations:
    argocd.argoproj.io/sync-wave: "20"
spec:
  channel: v1.3-eus
  name: ibm-mq 
  source: ibm-operator-catalog 
  sourceNamespace: openshift-marketplace 
